horario2021/urls.py
from django.urls import path
from . import views


app_name= 'horario2021'

urlpatterns  = [
    path('<int:anno>/', views.index, name='index'),
    path('<int:anno>/cambiosemana', views.cambiosemana, name='cambiosemana'),
    path('<int:anno>/cambiodia/<int:dia>/', views.cambiodia, name='cambiodia'),
    path('<int:anno>/cambiodias/', views.cambiodias, name='cambiodias'),
    path('<int:anno>/intercambiodia0/', views.modelformset_view, name='modelformset_view'),
    path('<int:anno>/intercambiodia/', views.formset_view, name='formset_view'),
    path('jornadas/', views.jornadas, name='jornadas'),
    path('<int:anno>/semana/<int:dia>/', views.semana, name='semana'),
    path('<int:anno>/esquema/<str:tareas>/', views.esquema, name='esquema'),
    path('<int:anno>/anual/<str:persona>/', views.anual_persona, name='anual_persona'),
    path('<int:anno>/horas/', views.horas, name='horas'),
    path('<int:anno>/dias/', views.dias, name='dias'),
    path('<int:anno>/bonificadas/', views.bonificadas, name='bonificadas'),
    path('<int:anno>/importes/<int:mese>', views.importes, name='importes'),
    path('<int:anno>/vacaciones/<str:tareas>/',views.vacaciones, name='vacaciones'),
    path('<int:anno>/ver_turnos/', views.verturnos, name='ver_turnos'),
    path('<int:anno>/gestionar_festivos/<str:tareas>/',views.gestionar_festivos, name='gestionar_festivos'),
    path('<int:anno>/vacas_solicitadas/<str:grupo>/', views.vacas_solicitadas, name='vacas_solicitadas'),
           ]

horario2021/templates/horario2021/anual_persona.html
{% extends 'horario2021/base.html'%}

{% load l10n %}

{% load static %}



{% block content%}

<h3 align='center'>{{ persona }}</h3>

<div style="column-count:5" id='turno'>
{% for semana in turnos %}

<table class="table">
    <thead><th> Día semana </th><th> Fecha </th><th> Turno </th></thead>
    {% for dia in semana %}
    <tbody>
	    <tr><td>{{ dia.fecha| date:"l" | localize }}</td>
		    <td><a href="/{{ jahr }}/cambiodia/{{ dia.id }}/" target="_blank">{{ dia.fecha|date:"SHORT_DATE_FORMAT" }}</a></td>
		<td>{{ dia.turnodia__etiqueta }}</td></tr>
    </tbody>
    {% endfor %}
</table>

<br>
{% endfor %}

</div>



<h3 align='center'> Festivos trabajados y compensados </h3>
<div  id='turno'>
<table style="width:50%">
  <thead>
    <th>Festivo trabajado --> horas</th>
  </thead>
  <tbody>
  {% for dia in festivos_horas %}
    <tr><td> {{ dia.0 }}--> {{ dia.1 }}</td></tr>
  {% endfor %} 
  </tbody>
</table>
<table style="width:50%">
  <thead>
    <th>Festivo compensado</th>
  </thead>
  <tbody>
  {% for dia in compensados %}
    <tr><td> {{ dia }} </td></tr>
  {% endfor %} 
  </tbody>
</table>
</div>


    <script>
         let tur = document.getElementById("turno");
         let turse = tur.getElementsByTagName("td");
         for (i=1; i < 1400 ;i++) {
         if (turse[i].innerText.includes("tarde16")||turse[i].innerText.includes('noche')) { turse[i].style.background = "#33ceff"; }
                else if (turse[i].innerText.includes("libre")||turse[i].innerText.includes('vacas')||turse[i].innerText.includes('comp')) {turse[i].style.background = "#f0fa8f";}    
                else if (turse[i].innerText.includes("e15")||turse[i].innerText.includes("e14")) { turse[i].style.background = " #5eca68"; }
                else if (turse[i].innerText.includes("mañana")) { turse[i].style.background = "#ff5733"; }
                else if (turse[i].innerText.includes("partid")) { turse[i].style.background = "#c483fa"; }
                else { turse[i].style.background = "light blue"; }
          }
    </script>



{% endblock %}

horario2021/templates/horario2021/base.html
{% load static %}

<html>
    <head>    
        <title> horario dpto soporte 2021</title>
	<link rel="stylesheet" href="{% static 'css/horario2021.css' %}">
	<link rel="stylesheet" href="{% static 'css/anual.css' %}">


    </head>

    <body>
        <div class="page-header">
	    <h1><a href="">horario soporte <script>document.write( new Date().getFullYear() );</script></a></h1>
	        {% if user.is_authenticated %}                    
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
                {% endif %} 

        </div>
       
	<div class="content">
            {% block content %}



            {% endblock %}
        </div>

    </body>


</html>

horario2021/templates/horario2021/cambios_turnos.html
{% extends 'horario2021/base.html' %}


{% block content %}   
<form action="" method="post">     
    {% csrf_token %}
    <p align='center'>
    <table>
    {{ form.as_table }}
    </table>
    <br> 	
    <button type="submit">
        Cambia
    </button>
    </p>           
</form>
{% endblock %}   

horario2021/templates/horario2021/cambiosemanaok.html
{% extends 'horario2021/base.html' %}
{% block  content %} 
Actualizado horario 
<br><br>

Tech:  {{ turno_tech }}
<br><br>

<br><br>

Turno para la semana: {{ turnosemana }}
<br><br>

<h3>RECUERDA REVISAR EL TURNO DEL LUNES -- GUARDIAS</h3>
<br><br>




<br>
<a href="{% url 'horario2021:cambiosemana' jahr %}">volver</a>




{% endblock %} 

horario2021/templates/horario2021/dias_trabajados.html
{% extends 'horario2021/base.html'%}

{% block content %}

Días trabajados en cada mes 

<table class="table">
	<thead><th> Tech  </th><th> enero </th><th> febrero </th><th> marzo </th><th> abril </th><th> mayo </th><th> junio </th><th> julio </th><th> agosto </th><th> septiembre </th><th> octubre </th><th> noviembre </th><th> diciembre </th><th>anuales</th></thead>
    <tbody>
    {% for persona in matriz %}
    <tr><td>{{ persona.0 }}</td><td>{{ persona.1 }}</td><td>{{ persona.2 }}</td><td>{{ persona.3 }}</td><td>{{ persona.4 }}</td><td>{{ persona.5 }}</td><td>{{ persona.6 }}</td><td>{{ persona.7 }}</td><td>{{ persona.8 }}</td><td>{{ persona.9 }}</td><td>{{ persona.10 }}</td><td>{{ persona.11 }}</td><td>{{ persona.12 }}</td><td>{{ persona.13 }}</td></tr>	
    {% endfor %}
    </tbody>
</table>


{% endblock %}

horario2021/templates/horario2021/esquema.html
{% extends 'horario2021/base.html'%}


{% block content %}

{% load static %}


<br>
<div class='pegada'>
<table id='nomostrar0'>
    <thead>
	    <tr>
	    <th>Día</th>
	      {% for tanda in tandas %}
	      <th style='font-size:10px'>{{ tanda }}</th>
	    {% endfor %}
	    <tr>
    </thead>

    <tbody>
    {% for dia in matriz %}
    <tr><th style='font-size:12px; text-align:left'>{{ dia.0 | date:"l j.m.Y"}}</th>
	    {% for tanda in dia.1.values %}
            <td>{{ tanda }}</td>
	    {% endfor %}
    </tr>  

    {% endfor %}
          
    </tbody>

</table>
</div>



<script> 	      
    let tur = document.getElementById("nomostrar0");               
    let turse = tur.getElementsByTagName("td");               
    for (i=0; i < turse.length ;i++) {               
        if (turse[i].innerText.includes("0"))  { 
	        turse[i].innerHTML=" "}               
	}          
</script> 


{% endblock %}

horario2021/templates/horario2021/horas_trabajadas.html
{% extends 'horario2021/base.html'%}

{% block content %}



<table class="table">
	<thead><th> Tech  </th><th> enero </th><th> febrero </th><th> marzo </th><th> abril </th><th> mayo </th><th> junio </th><th> julio </th><th> agosto </th><th> septiembre </th><th> octubre </th><th> noviembre </th><th> diciembre </th><th>anuales</th></thead>
    <tbody>
    {% for persona in matriz %}
    <tr><td class='primera'>{{ persona.0 }}</td><td>{{ persona.1 }}</td><td>{{ persona.2 }}</td><td>{{ persona.3 }}</td><td>{{ persona.4 }}</td><td>{{ persona.5 }}</td><td>{{ persona.6 }}</td><td>{{ persona.7 }}</td><td>{{ persona.8 }}</td><td>{{ persona.9 }}</td><td>{{ persona.10 }}</td><td>{{ persona.11 }}</td><td>{{ persona.12 }}</td><td>{{ persona.13 }}</td></tr>	
    {% endfor %}
    </tbody>
</table>


{% endblock %}

horario2021/templates/horario2021/importes.html
{% extends 'horario2021/base.html'%}

{% block content %}


<h3>Importes correspondientes a la horas bonificadas para el mes {{ dia |date:"E" }} </h3>
<table class="table">
	<thead><th> Tech  </th><th> alias  </th><th> horas sábado </th><th> importe (€) sábados </th><th> horas bonificadas </th><th> importe (€) bonificadas </th></thead>
    <tbody>
    {% for persona in matriz %}
    <tr><td>{{ persona.0 }}</td><td>{{ persona.1 }}</td><td>{{ persona.2 }}</td><td>{{ persona.3 }}</td><td>{{ persona.4 }}</td><td>{{ persona.5 }}</td></tr>	
    {% endfor %}
    </tbody>
</table>

                



{% endblock %}

horario2021/templates/horario2021/index_2021.html
{% extends 'horario2021/base.html'%} 


{% block content  %}

{% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/calen.css' %}">


<div class="topnav">
	<a href="{% url 'horario2021:bonificadas' jahr %}" target="_blank">bonificadas</a>
    {% for i in lista_tecs %} 
    <a href="/{{ jahr }}/anual/{{ i.0 }}" target="_blank">{{ i.0 }}</a>
    {% endfor %}
</div>


{% if user.is_authenticated %}
  <div class="sidenav">
  <li><a href="{% url 'horario2021:cambiosemana' jahr %}" target="_blank">cambio semana</a></li>
  <li><a href="{% url 'horario2021:importes' jahr 1 %}" target="_blank">importes</a></li>
  <li><a href="{% url 'horario2021:cambiodias' jahr %}" target="_blank">cambio dias consecutivos</a></li>

  </div>
{% endif %}

<br>

<div id="horizontal">
<div id="vertical">
<div class = "month">
  <ul>
    <li>
      <span style="font-size:18px">Enero 2021</span>
    </li>
  </ul>
</div>
<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li><span class="nacional">1</span></li>
  <li>2</li>
  <li>3</li>
  <li><a href="{% url 'horario2021:semana' jahr 1 %}" target="_blank">4</a></li>
  <li>5</li>
  <li><span class="nacional">6</span></li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
</ul>
</div>
<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px"> febrero 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days">
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>-</li>   
  <li>-</li>  
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>
<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">marzo 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li><span class="comunidad">19</span></li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>
<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">abril 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li><span class="comunidad">1</span></li>
  <li><span class="nacional">2</span></li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
 <li>30</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">mayo 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li><span class="nacional">1</span></li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li><span class="local">13</span></li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li><span class="comunidad">17</span></li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>  
  <li>-</li>   
  <li>-</li>  
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">junio 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">julio 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">agosto 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li><span class="local">16</span></li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px"> septiembre 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>-</li>
  <li>-</li>  
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">octubre 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li><span class="nacional">12</span></li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">noviembre 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li><span class="nacional">1</span></li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li>6</li>
  <li>7</li>
  <li>8</li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li>25</li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>

<div id="vertical">
<div class="month">      
  <ul>
    <li>
      <span style="font-size:18px">diciembre 2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li>Lu</li>
  <li>Ma</li>
  <li>Mi</li>
  <li>Ju</li>
  <li>Vi</li>
  <li>Sa</li>
  <li>Do</li>
</ul>

<ul class="days"> 
  <li>-</li>
  <li>-</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
  <li>5</li>
  <li><span class="nacional">6</span></li>
  <li>7</li>
  <li><span class="nacional">8</span></li>
  <li>9</li>
  <li>10</li>
  <li>11</li>
  <li>12</li>
  <li>13</li>
  <li>14</li>
  <li>15</li>
  <li>16</li>
  <li>17</li>
  <li>18</li>
  <li>19</li>
  <li>20</li>
  <li>21</li>
  <li>22</li>
  <li>23</li>
  <li>24</li>
  <li><span class="nacional">25</span></li>
  <li>26</li>
  <li>27</li>
  <li>28</li>
  <li>29</li>
  <li>30</li>
  <li>31</li>
  <li>-</li>
  <li>-</li>
</ul>
</div>

</div>





{% comment %}
<div class="horario2021">
    {% for dia in dias %}
        {{ dia.fecha |date:"SHORT_DATE_FORMAT" }}
    {% endfor %}
</div>
<br>
{% endcomment %}

   
{% endblock %}

horario2021/templates/horario2021/intercambiodia.html
{% extends 'horario2021/base.html'%}



{# Display a form #} 
{% block content %}   
<div class="horario2021-form">



<form method="POST" enctype="multipart/form-data"> 

    {{ formset.management_data }} 

    {% csrf_token %}

    <p align='center'>
    <table border='1' align='center'>
            {{ formset }}
    </table>
    <br>
    <button type="submit">
        Cambia
    </button>
    </p>
</form> 


</div>
{% endblock %}   

horario2021/templates/horario2021/intercambiodia0.html
{% extends 'horario2021/base.html'%}



{# Display a form #} 
{% block content %}   
<div class="horario2021-form">



<form method="POST" enctype="multipart/form-data"> 

    {{ formset.management_data }} 

    {% csrf_token %}

    <p align='center'>
    <table border='1' align='center'>
        {{ formset.as_table }}
    </table>
    <br>
    <button type="submit">
        Cambia
    </button>
    </p>
</form> 


</div>
{% endblock %}   

horario2021/templates/horario2021/vacaciones_tarea.html
{% extends 'horario2021/base.html'%}

{% block content %}

Vacaciones de las personas con la tarea: {{ tarea }}
<br>
{% for fila in matriz %}
<table class="table">	
    <thead>
        <h3 style='text-align:center'>{{ fila.0 }}</h3>
    </thead>
    <tbody>
		{% for tipo, fechas in fila.1.items %}
		<tr>
			<th>{{ tipo }}</th>
			{% for fecha in fechas %}<td>{{ fecha | date:"SHORT_DATE_FORMAT" }}</td>{% endfor %}
    	</tr>
		{% endfor %}	
    </tbody>
</table>
<br>
{% endfor %}


Días festivos trabajados y compensados 
<br>
{% for fila in matriz_festivos %}

<table class="table">	
    <thead>
        <h3 style='text-align:center'>{{ fila.0 }}</h3>
    </thead>
    <tbody>
		<tr>
           <th>Festivos trabajados --> horas </th>
		   {% for dia  in fila.1 %}
           <td>{{ dia.0 }}--->  {{dia.1}} </td>{% endfor %}
        </tr>
		<tr>
           <th>Festivos compensados </th>
		   {% for dia  in fila.2 %}
           <td>{{ dia }} </td>{% endfor %}
        </tr>
    </tbody>
</table>
<br>


{% endfor %}

{% endblock %}